language: node_js
node_js:
  - 6.10.2
services:
  - postgresql
before_script:
  - npm install jest -g
  - psql -c 'create database "dms-test";' -U postgres

after_success: "cat ./coverage/lcov.info | coveralls"
