export const LOAD_CATEGORY_DOCUMENTS = 'LOAD_CATEGORY_DOCUMENTS';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const LOAD_PRIVATE_DOCUMENTS = 'LOAD_PRIVATE_DOCUMENTS';
export const LOAD_ROLE_DOCUMENTS = 'LOAD_ROLE_DOCUMENTS';
export const LOAD_PUBLIC_DOCUMENTS = 'LOAD_PUBLIC_DOCUMENTS';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
