export const SAVE_USER = 'SAVE_USER';
export const LOAD_ALL_USERS = 'LOAD_ALL_USERS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

